name: Update SixDeadBeefs/kali-ctf-default Repository
on:
  push:
    paths:
      - 'docker/default/Dockerfile'
      - 'docker/default/aliases'
jobs:
  sixdeadbeefs-default-Update:
    name: SixDeadBeefs/kali-ctf-default Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}        
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: docker/default/
          push: true
          tags: sixdeadbeefs/kali-ctf-default:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
