name: Update SixDeadBeefs Dockerhub Repo
on:
  push:
    paths:
      - 'Dockerfile'
      - 'aliases'
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - run: cd docker
      - run: docker build -t sixdeadbeefs/CTF:latest .
      - run: docker push sixdeadbeeds/CTF:latest      

